// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee
  var Api, axios;

  axios = require('axios');

  Api = class Api {
    constructor(token, url = "https://api.waditu.com/") {
      this.token = token;
      this.url = url;
    }

    async $(api_name, params, fields) {
      var body, d, data, df, i, items, j, k, len, len1, p, pli, ref, status, t;
      body = {
        token: this.token,
        api_name
      };
      if (params) {
        body.params = params;
      }
      if (fields) {
        delete params.fields;
        body.fields = fields;
      }
      ({data, status} = (await axios.post(this.url, body)));
      if (status !== 200) {
        throw new Error(data);
      }
      if (data.code) {
        throw data;
      }
      if (fields) {
        d = data.data;
        df = d.fields;
        d.fields = fields = fields.split(',');
        pli = fields.map((x) => {
          return df.indexOf(x);
        });
        items = [];
        ref = d.items;
        for (j = 0, len = ref.length; j < len; j++) {
          i = ref[j];
          t = [];
          for (k = 0, len1 = pli.length; k < len1; k++) {
            p = pli[k];
            t.push(i[p]);
          }
          items.push(t);
        }
        d.items = items;
      }
      return data.data;
    }

  };

  module.exports = function() {
    return new Proxy(new Api(...arguments), {
      get: (obj, prop) => {
        var f;
        f = obj[prop];
        if (!f) {
          return obj.$.bind(obj, prop);
        }
      }
    });
  };

}).call(this);
